// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ShootMatch.Infrastructure.Persistence;

#nullable disable

namespace ShootMatch.Infrastructure.Migrations;

[DbContext(typeof(ShootMatchDbContext))]
[Migration("20260520203216_ContactRealtimeFoundation")]
partial class ContactRealtimeFoundation
{
}
