// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using ShootMatch.Infrastructure.Persistence;

#nullable disable

namespace ShootMatch.Infrastructure.Migrations
{
    [DbContext(typeof(ShootMatchDbContext))]
    [Migration("20260529150000_AddStaffAccounts")]
    partial class AddStaffAccounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}